import Foundation
import CoreGraphics
import ArchonCore
#if canImport(WebKit)
import WebKit
#endif

/// Bridge connecting Apple AI Agent frameworks (Apple Intelligence, Local LLMs, Transformers) directly to the live Sandbox runtime.
public actor AgenticBridge {
    private weak var engine: SandboxEngine?
    private let toolRegistry = ToolRegistryActor()
    private let auditSink: any ArchonAuditSink
    
    public init(engine: SandboxEngine, auditSink: any ArchonAuditSink = NoOpArchonAuditSink()) {
        self.engine = engine
        self.auditSink = auditSink
    }
    
    // MARK: - Semantic DOM Extraction
    
    /// Extracts a token-optimized semantic representation of the current DOM state for LLM context windows.
    public func captureSemanticDOM(maxTokens: Int = 4096) async throws -> String {
        guard (0...SemanticDOMExtractor.maximumTokenBudget).contains(maxTokens) else {
            throw SandboxError.invalidExecutionRequest(
                "maxTokens must be between 0 and \(SemanticDOMExtractor.maximumTokenBudget)."
            )
        }
        guard let engine = engine else {
            throw SandboxError.engineDeallocated
        }
        
        let script = SemanticDOMExtractor.extractionScript(maxDepth: 8)
        let rawJSON = try await engine.evaluateScript(script)
        let markdown = SemanticDOMExtractor.jsonToSemanticMarkdown(rawJSON)
        return SemanticDOMExtractor.pruneToTokenBudget(markdown, maxTokens: maxTokens)
    }
    
    /// Extracts simplified JSON structure of the DOM tree.
    public func captureSemanticJSON(maxTokens: Int = 4096) async throws -> String {
        guard (0...SemanticDOMExtractor.maximumTokenBudget).contains(maxTokens) else {
            throw SandboxError.invalidExecutionRequest(
                "maxTokens must be between 0 and \(SemanticDOMExtractor.maximumTokenBudget)."
            )
        }
        guard let engine = engine else {
            throw SandboxError.engineDeallocated
        }
        let script = SemanticDOMExtractor.extractionScript(maxDepth: 8)
        let rawJSON = try await engine.evaluateScript(script)
        return SemanticDOMExtractor.pruneToTokenBudget(rawJSON, maxTokens: maxTokens)
    }
    
    // MARK: - Agent Code Patching
    
    /// Executes a dynamic code patch generated by the Agent, capturing visual and runtime execution feedback.
    public func applyAgentCodePatch(jsDelta: String, cssDelta: String? = nil) async throws -> AgentPatchResult {
        guard let engine = engine else {
            throw SandboxError.engineDeallocated
        }
        
        let startTime = Date()
        
        var combinedScript = "(function() {\n"
        combinedScript += "  try {\n"
        if let css = cssDelta, !css.isEmpty {
            let encodedCSS = String(
                data: (try? JSONEncoder().encode(css)) ?? Data("\"\"".utf8),
                encoding: .utf8
            ) ?? "\"\""
            let safeEncodedCSS = encodedCSS
                .replacingOccurrences(of: "\u{2028}", with: "\\u2028")
                .replacingOccurrences(of: "\u{2029}", with: "\\u2029")
            combinedScript += "    let style = document.createElement('style');\n"
            combinedScript += "    style.textContent = \(safeEncodedCSS);\n"
            combinedScript += "    document.head.appendChild(style);\n"
        }
        combinedScript += "    const patchResult = (function() {\n"
        combinedScript += "      \(jsDelta)\n"
        combinedScript += "    })();\n"
        combinedScript += "    return JSON.stringify({ success: true, result: patchResult !== undefined ? String(patchResult) : 'ok' });\n"
        combinedScript += "  } catch (err) {\n"
        combinedScript += "    return JSON.stringify({ success: false, error: err.toString(), stack: err.stack });\n"
        combinedScript += "  }\n"
        combinedScript += "})()"
        
        let rawResponse = try await engine.evaluateScript(combinedScript)
        let executionTime = Date().timeIntervalSince(startTime) * 1000.0
        let isSuccess = !rawResponse.contains("\"success\":false")
        
        var errorDesc: String?
        if !isSuccess {
            errorDesc = rawResponse
        }
        
        let result = AgentPatchResult(
            isSuccess: isSuccess,
            executionTimeMs: executionTime,
            rawOutput: rawResponse,
            errorDescription: errorDesc
        )
        await auditSink.record(ArchonAuditEvent(
            category: "sandbox",
            action: "code-patch",
            outcome: isSuccess ? "succeeded" : "failed",
            metadata: ["execution-ms": String(Int(executionTime))]
        ))
        return result
    }
    
    // MARK: - Tool Management
    
    /// Registers a tool that the Sandbox or LLM can invoke.
    public func registerTool(_ tool: any SandboxAgentTool) async {
        await toolRegistry.register(tool)
        if let engine = engine {
            await engine.registerTool(tool)
        }
    }
    
    /// Executes a registered tool directly through the Agent bridge.
    public func executeTool(name: String, argumentsJSON: String) async throws -> String {
        return try await toolRegistry.execute(toolName: name, argumentsJSON: argumentsJSON)
    }
    
    /// Returns Foundation Model function tool definitions for all registered tools.
    public func getToolDefinitions() async -> [FoundationModelToolDefinition] {
        await toolRegistry.exportFoundationModelToolDefinitions()
    }
}
